/**
 * AUTOGENERATED — do not edit by hand.
 *
 * Source:    daanyam-webapp/scripts/generate-rishte-muhurat-data.ts
 * Engine:    Swiss Ephemeris via lib/astrology/engine/panchang
 * Location:  Delhi / Drik Panchang convention (lat 28.6139, lon 77.209)
 * Generated: 2026-05-15T13:17:30.930Z
 *
 * Regenerate:
 *   cd daanyam-webapp
 *   npx tsx scripts/generate-rishte-muhurat-data.ts --year 2026
 */

export type VivahMuhuratEntry = {
  date: string;        // "Thu, 15 Jan"
  isoDate: string;     // "2026-01-15"
  weekday: number;     // 0 = Sunday
  tithi: string;
  nakshatra: string;
  timeWindow: string;
  score: "Excellent" | "Good" | "Okay";
};

export type VivahMuhuratMonth = {
  name: string;
  year: number;
  monthNumber: number;
  entries: VivahMuhuratEntry[];
};

export const VIVAH_MUHURAT_YEAR = 2026;
export const VIVAH_MUHURAT_LOCATION = "Delhi / Drik Panchang convention";
export const VIVAH_MUHURAT_VERIFIED = true;

export const VIVAH_MUHURAT_MONTHS: VivahMuhuratMonth[] = [
  {
    "name": "January 2026",
    "year": 2026,
    "monthNumber": 1,
    "entries": [
      {
        "date": "Thu, 1 Jan",
        "isoDate": "2026-01-01",
        "weekday": 4,
        "tithi": "त्रयोदशी",
        "nakshatra": "आर्द्रा",
        "timeWindow": "12:01 am – 12:49 am",
        "score": "Good"
      },
      {
        "date": "Mon, 5 Jan",
        "isoDate": "2026-01-05",
        "weekday": 1,
        "tithi": "द्वितीया (कृ)",
        "nakshatra": "मघा",
        "timeWindow": "12:03 am – 12:51 am",
        "score": "Good"
      },
      {
        "date": "Tue, 6 Jan",
        "isoDate": "2026-01-06",
        "weekday": 2,
        "tithi": "तृतीया (कृ)",
        "nakshatra": "पूर्व फल्गुनी",
        "timeWindow": "12:03 am – 12:51 am",
        "score": "Good"
      },
      {
        "date": "Wed, 7 Jan",
        "isoDate": "2026-01-07",
        "weekday": 3,
        "tithi": "चतुर्थी (कृ)",
        "nakshatra": "उत्तर फल्गुनी",
        "timeWindow": "9:15 pm – 10:45 pm",
        "score": "Good"
      },
      {
        "date": "Thu, 8 Jan",
        "isoDate": "2026-01-08",
        "weekday": 4,
        "tithi": "पञ्चमी (कृ)",
        "nakshatra": "हस्ता",
        "timeWindow": "12:04 am – 12:52 am",
        "score": "Good"
      },
      {
        "date": "Fri, 9 Jan",
        "isoDate": "2026-01-09",
        "weekday": 5,
        "tithi": "षष्ठी (कृ)",
        "nakshatra": "चित्रा",
        "timeWindow": "9:16 pm – 10:46 pm",
        "score": "Good"
      },
      {
        "date": "Thu, 15 Jan",
        "isoDate": "2026-01-15",
        "weekday": 4,
        "tithi": "द्वादशी (कृ)",
        "nakshatra": "मूल",
        "timeWindow": "12:07 am – 12:55 am",
        "score": "Good"
      },
      {
        "date": "Fri, 16 Jan",
        "isoDate": "2026-01-16",
        "weekday": 5,
        "tithi": "त्रयोदशी (कृ)",
        "nakshatra": "पूर्वाषाढ़ा",
        "timeWindow": "9:15 pm – 10:45 pm",
        "score": "Good"
      },
      {
        "date": "Mon, 19 Jan",
        "isoDate": "2026-01-19",
        "weekday": 1,
        "tithi": "प्रतिपदा",
        "nakshatra": "धनिष्ठा",
        "timeWindow": "12:08 am – 12:56 am",
        "score": "Excellent"
      },
      {
        "date": "Tue, 20 Jan",
        "isoDate": "2026-01-20",
        "weekday": 2,
        "tithi": "द्वितीया",
        "nakshatra": "शतभिषा",
        "timeWindow": "12:08 am – 12:56 am",
        "score": "Okay"
      },
      {
        "date": "Wed, 21 Jan",
        "isoDate": "2026-01-21",
        "weekday": 3,
        "tithi": "तृतीया",
        "nakshatra": "पूर्वभाद्रपदा",
        "timeWindow": "9:15 pm – 10:45 pm",
        "score": "Good"
      },
      {
        "date": "Thu, 22 Jan",
        "isoDate": "2026-01-22",
        "weekday": 4,
        "tithi": "चतुर्थी",
        "nakshatra": "उत्तरभाद्रपदा",
        "timeWindow": "12:09 am – 12:57 am",
        "score": "Excellent"
      },
      {
        "date": "Fri, 23 Jan",
        "isoDate": "2026-01-23",
        "weekday": 5,
        "tithi": "पञ्चमी",
        "nakshatra": "रेवती",
        "timeWindow": "9:14 pm – 10:44 pm",
        "score": "Excellent"
      },
      {
        "date": "Sun, 25 Jan",
        "isoDate": "2026-01-25",
        "weekday": 0,
        "tithi": "सप्तमी",
        "nakshatra": "भरणी",
        "timeWindow": "12:10 am – 12:58 am",
        "score": "Good"
      },
      {
        "date": "Mon, 26 Jan",
        "isoDate": "2026-01-26",
        "weekday": 1,
        "tithi": "अष्टमी",
        "nakshatra": "कृत्तिका",
        "timeWindow": "12:10 am – 12:58 am",
        "score": "Excellent"
      },
      {
        "date": "Tue, 27 Jan",
        "isoDate": "2026-01-27",
        "weekday": 2,
        "tithi": "नवमी",
        "nakshatra": "रोहिणी",
        "timeWindow": "12:10 am – 12:58 am",
        "score": "Good"
      },
      {
        "date": "Wed, 28 Jan",
        "isoDate": "2026-01-28",
        "weekday": 3,
        "tithi": "दशमी",
        "nakshatra": "मृगशीर्षा",
        "timeWindow": "9:12 pm – 10:42 pm",
        "score": "Good"
      },
      {
        "date": "Thu, 29 Jan",
        "isoDate": "2026-01-29",
        "weekday": 4,
        "tithi": "एकादशी",
        "nakshatra": "आर्द्रा",
        "timeWindow": "12:11 am – 12:59 am",
        "score": "Excellent"
      },
      {
        "date": "Fri, 30 Jan",
        "isoDate": "2026-01-30",
        "weekday": 5,
        "tithi": "द्वादशी",
        "nakshatra": "पुनर्वसु",
        "timeWindow": "9:11 pm – 10:41 pm",
        "score": "Excellent"
      }
    ]
  },
  {
    "name": "February 2026",
    "year": 2026,
    "monthNumber": 2,
    "entries": [
      {
        "date": "Mon, 2 Feb",
        "isoDate": "2026-02-02",
        "weekday": 1,
        "tithi": "प्रतिपदा (कृ)",
        "nakshatra": "पूर्व फल्गुनी",
        "timeWindow": "12:11 am – 12:59 am",
        "score": "Excellent"
      },
      {
        "date": "Tue, 3 Feb",
        "isoDate": "2026-02-03",
        "weekday": 2,
        "tithi": "द्वितीया (कृ)",
        "nakshatra": "उत्तर फल्गुनी",
        "timeWindow": "12:12 am – 1:00 am",
        "score": "Good"
      },
      {
        "date": "Wed, 4 Feb",
        "isoDate": "2026-02-04",
        "weekday": 3,
        "tithi": "तृतीया (कृ)",
        "nakshatra": "हस्ता",
        "timeWindow": "9:09 pm – 10:39 pm",
        "score": "Okay"
      },
      {
        "date": "Thu, 5 Feb",
        "isoDate": "2026-02-05",
        "weekday": 4,
        "tithi": "चतुर्थी (कृ)",
        "nakshatra": "चित्रा",
        "timeWindow": "12:12 am – 1:00 am",
        "score": "Good"
      },
      {
        "date": "Fri, 6 Feb",
        "isoDate": "2026-02-06",
        "weekday": 5,
        "tithi": "पञ्चमी (कृ)",
        "nakshatra": "स्वाती",
        "timeWindow": "9:08 pm – 10:38 pm",
        "score": "Good"
      },
      {
        "date": "Mon, 9 Feb",
        "isoDate": "2026-02-09",
        "weekday": 1,
        "tithi": "अष्टमी (कृ)",
        "nakshatra": "अनुराधा",
        "timeWindow": "12:12 am – 1:00 am",
        "score": "Excellent"
      },
      {
        "date": "Thu, 12 Feb",
        "isoDate": "2026-02-12",
        "weekday": 4,
        "tithi": "दशमी (कृ)",
        "nakshatra": "पूर्वाषाढ़ा",
        "timeWindow": "12:12 am – 1:00 am",
        "score": "Good"
      },
      {
        "date": "Fri, 13 Feb",
        "isoDate": "2026-02-13",
        "weekday": 5,
        "tithi": "एकादशी (कृ)",
        "nakshatra": "उत्तराषाढ़ा",
        "timeWindow": "9:03 pm – 10:33 pm",
        "score": "Good"
      },
      {
        "date": "Wed, 18 Feb",
        "isoDate": "2026-02-18",
        "weekday": 3,
        "tithi": "प्रतिपदा",
        "nakshatra": "उत्तरभाद्रपदा",
        "timeWindow": "8:59 pm – 10:29 pm",
        "score": "Excellent"
      },
      {
        "date": "Thu, 19 Feb",
        "isoDate": "2026-02-19",
        "weekday": 4,
        "tithi": "द्वितीया",
        "nakshatra": "रेवती",
        "timeWindow": "12:12 am – 1:00 am",
        "score": "Excellent"
      },
      {
        "date": "Fri, 20 Feb",
        "isoDate": "2026-02-20",
        "weekday": 5,
        "tithi": "तृतीया",
        "nakshatra": "अश्विनी",
        "timeWindow": "8:57 pm – 10:27 pm",
        "score": "Excellent"
      },
      {
        "date": "Sun, 22 Feb",
        "isoDate": "2026-02-22",
        "weekday": 0,
        "tithi": "पञ्चमी",
        "nakshatra": "कृत्तिका",
        "timeWindow": "12:12 am – 1:00 am",
        "score": "Okay"
      },
      {
        "date": "Mon, 23 Feb",
        "isoDate": "2026-02-23",
        "weekday": 1,
        "tithi": "षष्ठी",
        "nakshatra": "रोहिणी",
        "timeWindow": "12:11 am – 12:59 am",
        "score": "Excellent"
      },
      {
        "date": "Tue, 24 Feb",
        "isoDate": "2026-02-24",
        "weekday": 2,
        "tithi": "सप्तमी",
        "nakshatra": "मृगशीर्षा",
        "timeWindow": "12:11 am – 12:59 am",
        "score": "Excellent"
      },
      {
        "date": "Thu, 26 Feb",
        "isoDate": "2026-02-26",
        "weekday": 4,
        "tithi": "दशमी",
        "nakshatra": "पुनर्वसु",
        "timeWindow": "12:11 am – 12:59 am",
        "score": "Excellent"
      },
      {
        "date": "Fri, 27 Feb",
        "isoDate": "2026-02-27",
        "weekday": 5,
        "tithi": "एकादशी",
        "nakshatra": "पुष्य",
        "timeWindow": "8:50 pm – 10:20 pm",
        "score": "Excellent"
      }
    ]
  },
  {
    "name": "March 2026",
    "year": 2026,
    "monthNumber": 3,
    "entries": [
      {
        "date": "Tue, 3 Mar",
        "isoDate": "2026-03-03",
        "weekday": 2,
        "tithi": "पूर्णिमा",
        "nakshatra": "उत्तर फल्गुनी",
        "timeWindow": "12:10 am – 12:58 am",
        "score": "Excellent"
      },
      {
        "date": "Wed, 4 Mar",
        "isoDate": "2026-03-04",
        "weekday": 3,
        "tithi": "प्रतिपदा (कृ)",
        "nakshatra": "हस्ता",
        "timeWindow": "8:45 pm – 10:15 pm",
        "score": "Okay"
      },
      {
        "date": "Thu, 5 Mar",
        "isoDate": "2026-03-05",
        "weekday": 4,
        "tithi": "द्वितीया (कृ)",
        "nakshatra": "चित्रा",
        "timeWindow": "12:10 am – 12:58 am",
        "score": "Good"
      },
      {
        "date": "Fri, 6 Mar",
        "isoDate": "2026-03-06",
        "weekday": 5,
        "tithi": "तृतीया (कृ)",
        "nakshatra": "स्वाती",
        "timeWindow": "8:43 pm – 10:13 pm",
        "score": "Good"
      },
      {
        "date": "Sun, 8 Mar",
        "isoDate": "2026-03-08",
        "weekday": 0,
        "tithi": "पञ्चमी (कृ)",
        "nakshatra": "अनुराधा",
        "timeWindow": "12:09 am – 12:57 am",
        "score": "Good"
      },
      {
        "date": "Mon, 9 Mar",
        "isoDate": "2026-03-09",
        "weekday": 1,
        "tithi": "षष्ठी (कृ)",
        "nakshatra": "ज्येष्ठा",
        "timeWindow": "12:09 am – 12:57 am",
        "score": "Good"
      },
      {
        "date": "Wed, 11 Mar",
        "isoDate": "2026-03-11",
        "weekday": 3,
        "tithi": "अष्टमी (कृ)",
        "nakshatra": "पूर्वाषाढ़ा",
        "timeWindow": "8:37 pm – 10:07 pm",
        "score": "Okay"
      },
      {
        "date": "Mon, 16 Mar",
        "isoDate": "2026-03-16",
        "weekday": 1,
        "tithi": "द्वादशी (कृ)",
        "nakshatra": "शतभिषा",
        "timeWindow": "12:07 am – 12:55 am",
        "score": "Good"
      },
      {
        "date": "Fri, 20 Mar",
        "isoDate": "2026-03-20",
        "weekday": 5,
        "tithi": "द्वितीया",
        "nakshatra": "अश्विनी",
        "timeWindow": "8:27 pm – 9:57 pm",
        "score": "Excellent"
      },
      {
        "date": "Sun, 22 Mar",
        "isoDate": "2026-03-22",
        "weekday": 0,
        "tithi": "चतुर्थी",
        "nakshatra": "रोहिणी",
        "timeWindow": "12:05 am – 12:53 am",
        "score": "Good"
      },
      {
        "date": "Mon, 23 Mar",
        "isoDate": "2026-03-23",
        "weekday": 1,
        "tithi": "पञ्चमी",
        "nakshatra": "मृगशीर्षा",
        "timeWindow": "12:05 am – 12:53 am",
        "score": "Excellent"
      },
      {
        "date": "Tue, 24 Mar",
        "isoDate": "2026-03-24",
        "weekday": 2,
        "tithi": "षष्ठी",
        "nakshatra": "आर्द्रा",
        "timeWindow": "12:04 am – 12:52 am",
        "score": "Okay"
      },
      {
        "date": "Wed, 25 Mar",
        "isoDate": "2026-03-25",
        "weekday": 3,
        "tithi": "सप्तमी",
        "nakshatra": "पुनर्वसु",
        "timeWindow": "8:21 pm – 9:51 pm",
        "score": "Excellent"
      },
      {
        "date": "Thu, 26 Mar",
        "isoDate": "2026-03-26",
        "weekday": 4,
        "tithi": "अष्टमी",
        "nakshatra": "पुष्य",
        "timeWindow": "12:04 am – 12:52 am",
        "score": "Excellent"
      },
      {
        "date": "Fri, 27 Mar",
        "isoDate": "2026-03-27",
        "weekday": 5,
        "tithi": "नवमी",
        "nakshatra": "आश्लेषा",
        "timeWindow": "8:19 pm – 9:49 pm",
        "score": "Okay"
      },
      {
        "date": "Sun, 29 Mar",
        "isoDate": "2026-03-29",
        "weekday": 0,
        "tithi": "एकादशी",
        "nakshatra": "पूर्व फल्गुनी",
        "timeWindow": "12:03 am – 12:51 am",
        "score": "Excellent"
      },
      {
        "date": "Mon, 30 Mar",
        "isoDate": "2026-03-30",
        "weekday": 1,
        "tithi": "द्वादशी",
        "nakshatra": "उत्तर फल्गुनी",
        "timeWindow": "12:02 am – 12:50 am",
        "score": "Excellent"
      }
    ]
  },
  {
    "name": "April 2026",
    "year": 2026,
    "monthNumber": 4,
    "entries": [
      {
        "date": "Thu, 2 Apr",
        "isoDate": "2026-04-02",
        "weekday": 4,
        "tithi": "पूर्णिमा",
        "nakshatra": "स्वाती",
        "timeWindow": "12:02 am – 12:50 am",
        "score": "Excellent"
      },
      {
        "date": "Fri, 3 Apr",
        "isoDate": "2026-04-03",
        "weekday": 5,
        "tithi": "प्रतिपदा (कृ)",
        "nakshatra": "विशाखा",
        "timeWindow": "8:11 pm – 9:41 pm",
        "score": "Good"
      },
      {
        "date": "Mon, 6 Apr",
        "isoDate": "2026-04-06",
        "weekday": 1,
        "tithi": "चतुर्थी (कृ)",
        "nakshatra": "मूल",
        "timeWindow": "12:00 am – 12:48 am",
        "score": "Good"
      },
      {
        "date": "Wed, 8 Apr",
        "isoDate": "2026-04-08",
        "weekday": 3,
        "tithi": "षष्ठी (कृ)",
        "nakshatra": "पूर्वाषाढ़ा",
        "timeWindow": "8:05 pm – 9:35 pm",
        "score": "Okay"
      },
      {
        "date": "Thu, 9 Apr",
        "isoDate": "2026-04-09",
        "weekday": 4,
        "tithi": "सप्तमी (कृ)",
        "nakshatra": "उत्तराषाढ़ा",
        "timeWindow": "11:59 pm – 12:47 am",
        "score": "Good"
      },
      {
        "date": "Fri, 10 Apr",
        "isoDate": "2026-04-10",
        "weekday": 5,
        "tithi": "अष्टमी (कृ)",
        "nakshatra": "श्रवण",
        "timeWindow": "8:03 pm – 9:33 pm",
        "score": "Good"
      },
      {
        "date": "Mon, 13 Apr",
        "isoDate": "2026-04-13",
        "weekday": 1,
        "tithi": "एकादशी (कृ)",
        "nakshatra": "पूर्वभाद्रपदा",
        "timeWindow": "11:58 pm – 12:46 am",
        "score": "Good"
      },
      {
        "date": "Tue, 14 Apr",
        "isoDate": "2026-04-14",
        "weekday": 2,
        "tithi": "द्वादशी (कृ)",
        "nakshatra": "उत्तरभाद्रपदा",
        "timeWindow": "11:58 pm – 12:46 am",
        "score": "Good"
      },
      {
        "date": "Wed, 15 Apr",
        "isoDate": "2026-04-15",
        "weekday": 3,
        "tithi": "त्रयोदशी (कृ)",
        "nakshatra": "रेवती",
        "timeWindow": "7:57 pm – 9:27 pm",
        "score": "Good"
      },
      {
        "date": "Sun, 19 Apr",
        "isoDate": "2026-04-19",
        "weekday": 0,
        "tithi": "द्वितीया",
        "nakshatra": "रोहिणी",
        "timeWindow": "11:57 pm – 12:45 am",
        "score": "Excellent"
      },
      {
        "date": "Mon, 20 Apr",
        "isoDate": "2026-04-20",
        "weekday": 1,
        "tithi": "तृतीया",
        "nakshatra": "मृगशीर्षा",
        "timeWindow": "11:57 pm – 12:45 am",
        "score": "Excellent"
      },
      {
        "date": "Tue, 21 Apr",
        "isoDate": "2026-04-21",
        "weekday": 2,
        "tithi": "पञ्चमी",
        "nakshatra": "आर्द्रा",
        "timeWindow": "11:57 pm – 12:45 am",
        "score": "Okay"
      },
      {
        "date": "Wed, 22 Apr",
        "isoDate": "2026-04-22",
        "weekday": 3,
        "tithi": "षष्ठी",
        "nakshatra": "पुष्य",
        "timeWindow": "7:50 pm – 9:20 pm",
        "score": "Excellent"
      },
      {
        "date": "Thu, 23 Apr",
        "isoDate": "2026-04-23",
        "weekday": 4,
        "tithi": "सप्तमी",
        "nakshatra": "आश्लेषा",
        "timeWindow": "11:56 pm – 12:44 am",
        "score": "Excellent"
      },
      {
        "date": "Fri, 24 Apr",
        "isoDate": "2026-04-24",
        "weekday": 5,
        "tithi": "अष्टमी",
        "nakshatra": "मघा",
        "timeWindow": "7:48 pm – 9:18 pm",
        "score": "Good"
      },
      {
        "date": "Sun, 26 Apr",
        "isoDate": "2026-04-26",
        "weekday": 0,
        "tithi": "दशमी",
        "nakshatra": "उत्तर फल्गुनी",
        "timeWindow": "11:56 pm – 12:44 am",
        "score": "Good"
      },
      {
        "date": "Mon, 27 Apr",
        "isoDate": "2026-04-27",
        "weekday": 1,
        "tithi": "एकादशी",
        "nakshatra": "हस्ता",
        "timeWindow": "11:55 pm – 12:43 am",
        "score": "Excellent"
      },
      {
        "date": "Tue, 28 Apr",
        "isoDate": "2026-04-28",
        "weekday": 2,
        "tithi": "द्वादशी",
        "nakshatra": "चित्रा",
        "timeWindow": "11:55 pm – 12:43 am",
        "score": "Good"
      },
      {
        "date": "Wed, 29 Apr",
        "isoDate": "2026-04-29",
        "weekday": 3,
        "tithi": "त्रयोदशी",
        "nakshatra": "स्वाती",
        "timeWindow": "7:43 pm – 9:13 pm",
        "score": "Okay"
      }
    ]
  },
  {
    "name": "May 2026",
    "year": 2026,
    "monthNumber": 5,
    "entries": [
      {
        "date": "Fri, 1 May",
        "isoDate": "2026-05-01",
        "weekday": 5,
        "tithi": "पूर्णिमा",
        "nakshatra": "विशाखा",
        "timeWindow": "7:42 pm – 9:12 pm",
        "score": "Excellent"
      },
      {
        "date": "Mon, 4 May",
        "isoDate": "2026-05-04",
        "weekday": 1,
        "tithi": "तृतीया (कृ)",
        "nakshatra": "मूल",
        "timeWindow": "11:55 pm – 12:43 am",
        "score": "Good"
      },
      {
        "date": "Wed, 6 May",
        "isoDate": "2026-05-06",
        "weekday": 3,
        "tithi": "चतुर्थी (कृ)",
        "nakshatra": "उत्तराषाढ़ा",
        "timeWindow": "7:38 pm – 9:08 pm",
        "score": "Okay"
      },
      {
        "date": "Thu, 7 May",
        "isoDate": "2026-05-07",
        "weekday": 4,
        "tithi": "पञ्चमी (कृ)",
        "nakshatra": "श्रवण",
        "timeWindow": "11:54 pm – 12:42 am",
        "score": "Good"
      },
      {
        "date": "Fri, 8 May",
        "isoDate": "2026-05-08",
        "weekday": 5,
        "tithi": "षष्ठी (कृ)",
        "nakshatra": "धनिष्ठा",
        "timeWindow": "7:36 pm – 9:06 pm",
        "score": "Okay"
      },
      {
        "date": "Tue, 12 May",
        "isoDate": "2026-05-12",
        "weekday": 2,
        "tithi": "दशमी (कृ)",
        "nakshatra": "उत्तरभाद्रपदा",
        "timeWindow": "11:54 pm – 12:42 am",
        "score": "Good"
      },
      {
        "date": "Wed, 13 May",
        "isoDate": "2026-05-13",
        "weekday": 3,
        "tithi": "एकादशी (कृ)",
        "nakshatra": "रेवती",
        "timeWindow": "7:33 pm – 9:03 pm",
        "score": "Good"
      },
      {
        "date": "Thu, 14 May",
        "isoDate": "2026-05-14",
        "weekday": 4,
        "tithi": "द्वादशी (कृ)",
        "nakshatra": "भरणी",
        "timeWindow": "11:54 pm – 12:42 am",
        "score": "Good"
      },
      {
        "date": "Fri, 15 May",
        "isoDate": "2026-05-15",
        "weekday": 5,
        "tithi": "त्रयोदशी (कृ)",
        "nakshatra": "कृत्तिका",
        "timeWindow": "7:32 pm – 9:02 pm",
        "score": "Okay"
      },
      {
        "date": "Sun, 17 May",
        "isoDate": "2026-05-17",
        "weekday": 0,
        "tithi": "प्रतिपदा",
        "nakshatra": "मृगशीर्षा",
        "timeWindow": "11:54 pm – 12:42 am",
        "score": "Excellent"
      },
      {
        "date": "Mon, 18 May",
        "isoDate": "2026-05-18",
        "weekday": 1,
        "tithi": "द्वितीया",
        "nakshatra": "आर्द्रा",
        "timeWindow": "11:54 pm – 12:42 am",
        "score": "Excellent"
      },
      {
        "date": "Tue, 19 May",
        "isoDate": "2026-05-19",
        "weekday": 2,
        "tithi": "तृतीया",
        "nakshatra": "पुनर्वसु",
        "timeWindow": "11:54 pm – 12:42 am",
        "score": "Excellent"
      },
      {
        "date": "Wed, 20 May",
        "isoDate": "2026-05-20",
        "weekday": 3,
        "tithi": "चतुर्थी",
        "nakshatra": "पुष्य",
        "timeWindow": "7:29 pm – 8:59 pm",
        "score": "Good"
      },
      {
        "date": "Thu, 21 May",
        "isoDate": "2026-05-21",
        "weekday": 4,
        "tithi": "पञ्चमी",
        "nakshatra": "आश्लेषा",
        "timeWindow": "11:54 pm – 12:42 am",
        "score": "Excellent"
      },
      {
        "date": "Fri, 22 May",
        "isoDate": "2026-05-22",
        "weekday": 5,
        "tithi": "षष्ठी",
        "nakshatra": "मघा",
        "timeWindow": "7:28 pm – 8:58 pm",
        "score": "Good"
      },
      {
        "date": "Sun, 24 May",
        "isoDate": "2026-05-24",
        "weekday": 0,
        "tithi": "नवमी",
        "nakshatra": "उत्तर फल्गुनी",
        "timeWindow": "11:55 pm – 12:43 am",
        "score": "Good"
      },
      {
        "date": "Mon, 25 May",
        "isoDate": "2026-05-25",
        "weekday": 1,
        "tithi": "दशमी",
        "nakshatra": "हस्ता",
        "timeWindow": "11:55 pm – 12:43 am",
        "score": "Good"
      },
      {
        "date": "Tue, 26 May",
        "isoDate": "2026-05-26",
        "weekday": 2,
        "tithi": "एकादशी",
        "nakshatra": "चित्रा",
        "timeWindow": "11:55 pm – 12:43 am",
        "score": "Good"
      },
      {
        "date": "Wed, 27 May",
        "isoDate": "2026-05-27",
        "weekday": 3,
        "tithi": "एकादशी",
        "nakshatra": "स्वाती",
        "timeWindow": "7:26 pm – 8:56 pm",
        "score": "Good"
      },
      {
        "date": "Thu, 28 May",
        "isoDate": "2026-05-28",
        "weekday": 4,
        "tithi": "द्वादशी",
        "nakshatra": "विशाखा",
        "timeWindow": "11:55 pm – 12:43 am",
        "score": "Excellent"
      },
      {
        "date": "Fri, 29 May",
        "isoDate": "2026-05-29",
        "weekday": 5,
        "tithi": "त्रयोदशी",
        "nakshatra": "अनुराधा",
        "timeWindow": "7:25 pm – 8:55 pm",
        "score": "Excellent"
      },
      {
        "date": "Sun, 31 May",
        "isoDate": "2026-05-31",
        "weekday": 0,
        "tithi": "पूर्णिमा",
        "nakshatra": "मूल",
        "timeWindow": "11:56 pm – 12:44 am",
        "score": "Okay"
      }
    ]
  },
  {
    "name": "June 2026",
    "year": 2026,
    "monthNumber": 6,
    "entries": [
      {
        "date": "Mon, 1 Jun",
        "isoDate": "2026-06-01",
        "weekday": 1,
        "tithi": "प्रतिपदा (कृ)",
        "nakshatra": "पूर्वाषाढ़ा",
        "timeWindow": "11:56 pm – 12:44 am",
        "score": "Good"
      },
      {
        "date": "Wed, 3 Jun",
        "isoDate": "2026-06-03",
        "weekday": 3,
        "tithi": "तृतीया (कृ)",
        "nakshatra": "श्रवण",
        "timeWindow": "7:24 pm – 8:54 pm",
        "score": "Okay"
      },
      {
        "date": "Thu, 4 Jun",
        "isoDate": "2026-06-04",
        "weekday": 4,
        "tithi": "चतुर्थी (कृ)",
        "nakshatra": "श्रवण",
        "timeWindow": "11:56 pm – 12:44 am",
        "score": "Good"
      },
      {
        "date": "Fri, 5 Jun",
        "isoDate": "2026-06-05",
        "weekday": 5,
        "tithi": "पञ्चमी (कृ)",
        "nakshatra": "धनिष्ठा",
        "timeWindow": "7:24 pm – 8:54 pm",
        "score": "Okay"
      },
      {
        "date": "Mon, 8 Jun",
        "isoDate": "2026-06-08",
        "weekday": 1,
        "tithi": "अष्टमी (कृ)",
        "nakshatra": "उत्तरभाद्रपदा",
        "timeWindow": "11:57 pm – 12:45 am",
        "score": "Excellent"
      },
      {
        "date": "Wed, 10 Jun",
        "isoDate": "2026-06-10",
        "weekday": 3,
        "tithi": "दशमी (कृ)",
        "nakshatra": "अश्विनी",
        "timeWindow": "7:24 pm – 8:54 pm",
        "score": "Good"
      },
      {
        "date": "Thu, 11 Jun",
        "isoDate": "2026-06-11",
        "weekday": 4,
        "tithi": "एकादशी (कृ)",
        "nakshatra": "भरणी",
        "timeWindow": "11:57 pm – 12:45 am",
        "score": "Good"
      },
      {
        "date": "Fri, 12 Jun",
        "isoDate": "2026-06-12",
        "weekday": 5,
        "tithi": "द्वादशी (कृ)",
        "nakshatra": "कृत्तिका",
        "timeWindow": "7:24 pm – 8:54 pm",
        "score": "Okay"
      },
      {
        "date": "Tue, 16 Jun",
        "isoDate": "2026-06-16",
        "weekday": 2,
        "tithi": "द्वितीया",
        "nakshatra": "पुष्य",
        "timeWindow": "11:58 pm – 12:46 am",
        "score": "Excellent"
      },
      {
        "date": "Wed, 17 Jun",
        "isoDate": "2026-06-17",
        "weekday": 3,
        "tithi": "तृतीया",
        "nakshatra": "आश्लेषा",
        "timeWindow": "7:24 pm – 8:54 pm",
        "score": "Good"
      },
      {
        "date": "Thu, 18 Jun",
        "isoDate": "2026-06-18",
        "weekday": 4,
        "tithi": "चतुर्थी",
        "nakshatra": "मघा",
        "timeWindow": "11:59 pm – 12:47 am",
        "score": "Good"
      },
      {
        "date": "Fri, 19 Jun",
        "isoDate": "2026-06-19",
        "weekday": 5,
        "tithi": "पञ्चमी",
        "nakshatra": "पूर्व फल्गुनी",
        "timeWindow": "7:24 pm – 8:54 pm",
        "score": "Excellent"
      },
      {
        "date": "Sun, 21 Jun",
        "isoDate": "2026-06-21",
        "weekday": 0,
        "tithi": "सप्तमी",
        "nakshatra": "हस्ता",
        "timeWindow": "11:59 pm – 12:47 am",
        "score": "Good"
      },
      {
        "date": "Mon, 22 Jun",
        "isoDate": "2026-06-22",
        "weekday": 1,
        "tithi": "अष्टमी",
        "nakshatra": "चित्रा",
        "timeWindow": "12:00 am – 12:48 am",
        "score": "Excellent"
      },
      {
        "date": "Wed, 24 Jun",
        "isoDate": "2026-06-24",
        "weekday": 3,
        "tithi": "दशमी",
        "nakshatra": "विशाखा",
        "timeWindow": "7:25 pm – 8:55 pm",
        "score": "Okay"
      },
      {
        "date": "Thu, 25 Jun",
        "isoDate": "2026-06-25",
        "weekday": 4,
        "tithi": "एकादशी",
        "nakshatra": "अनुराधा",
        "timeWindow": "12:00 am – 12:48 am",
        "score": "Excellent"
      },
      {
        "date": "Fri, 26 Jun",
        "isoDate": "2026-06-26",
        "weekday": 5,
        "tithi": "द्वादशी",
        "nakshatra": "ज्येष्ठा",
        "timeWindow": "7:26 pm – 8:56 pm",
        "score": "Good"
      },
      {
        "date": "Mon, 29 Jun",
        "isoDate": "2026-06-29",
        "weekday": 1,
        "tithi": "पूर्णिमा",
        "nakshatra": "पूर्वाषाढ़ा",
        "timeWindow": "12:01 am – 12:49 am",
        "score": "Excellent"
      }
    ]
  },
  {
    "name": "November 2026",
    "year": 2026,
    "monthNumber": 11,
    "entries": [
      {
        "date": "Mon, 2 Nov",
        "isoDate": "2026-11-02",
        "weekday": 1,
        "tithi": "अष्टमी (कृ)",
        "nakshatra": "मघा",
        "timeWindow": "11:41 pm – 12:29 am",
        "score": "Good"
      },
      {
        "date": "Wed, 4 Nov",
        "isoDate": "2026-11-04",
        "weekday": 3,
        "tithi": "दशमी (कृ)",
        "nakshatra": "उत्तर फल्गुनी",
        "timeWindow": "8:35 pm – 10:05 pm",
        "score": "Good"
      },
      {
        "date": "Thu, 5 Nov",
        "isoDate": "2026-11-05",
        "weekday": 4,
        "tithi": "एकादशी (कृ)",
        "nakshatra": "हस्ता",
        "timeWindow": "11:41 pm – 12:29 am",
        "score": "Good"
      },
      {
        "date": "Fri, 6 Nov",
        "isoDate": "2026-11-06",
        "weekday": 5,
        "tithi": "द्वादशी (कृ)",
        "nakshatra": "चित्रा",
        "timeWindow": "8:37 pm – 10:07 pm",
        "score": "Good"
      },
      {
        "date": "Tue, 10 Nov",
        "isoDate": "2026-11-10",
        "weekday": 2,
        "tithi": "प्रतिपदा",
        "nakshatra": "ज्येष्ठा",
        "timeWindow": "11:42 pm – 12:30 am",
        "score": "Okay"
      },
      {
        "date": "Wed, 11 Nov",
        "isoDate": "2026-11-11",
        "weekday": 3,
        "tithi": "द्वितीया",
        "nakshatra": "मूल",
        "timeWindow": "8:41 pm – 10:11 pm",
        "score": "Good"
      },
      {
        "date": "Thu, 12 Nov",
        "isoDate": "2026-11-12",
        "weekday": 4,
        "tithi": "तृतीया",
        "nakshatra": "पूर्वाषाढ़ा",
        "timeWindow": "11:42 pm – 12:30 am",
        "score": "Excellent"
      },
      {
        "date": "Fri, 13 Nov",
        "isoDate": "2026-11-13",
        "weekday": 5,
        "tithi": "चतुर्थी",
        "nakshatra": "उत्तराषाढ़ा",
        "timeWindow": "8:42 pm – 10:12 pm",
        "score": "Good"
      },
      {
        "date": "Sun, 15 Nov",
        "isoDate": "2026-11-15",
        "weekday": 0,
        "tithi": "षष्ठी",
        "nakshatra": "धनिष्ठा",
        "timeWindow": "11:42 pm – 12:30 am",
        "score": "Okay"
      },
      {
        "date": "Mon, 16 Nov",
        "isoDate": "2026-11-16",
        "weekday": 1,
        "tithi": "सप्तमी",
        "nakshatra": "शतभिषा",
        "timeWindow": "11:43 pm – 12:31 am",
        "score": "Excellent"
      },
      {
        "date": "Tue, 17 Nov",
        "isoDate": "2026-11-17",
        "weekday": 2,
        "tithi": "अष्टमी",
        "nakshatra": "शतभिषा",
        "timeWindow": "11:43 pm – 12:31 am",
        "score": "Okay"
      },
      {
        "date": "Wed, 18 Nov",
        "isoDate": "2026-11-18",
        "weekday": 3,
        "tithi": "अष्टमी",
        "nakshatra": "पूर्वभाद्रपदा",
        "timeWindow": "8:46 pm – 10:16 pm",
        "score": "Good"
      },
      {
        "date": "Thu, 19 Nov",
        "isoDate": "2026-11-19",
        "weekday": 4,
        "tithi": "नवमी",
        "nakshatra": "उत्तरभाद्रपदा",
        "timeWindow": "11:43 pm – 12:31 am",
        "score": "Excellent"
      },
      {
        "date": "Fri, 20 Nov",
        "isoDate": "2026-11-20",
        "weekday": 5,
        "tithi": "दशमी",
        "nakshatra": "रेवती",
        "timeWindow": "8:48 pm – 10:18 pm",
        "score": "Excellent"
      },
      {
        "date": "Tue, 24 Nov",
        "isoDate": "2026-11-24",
        "weekday": 2,
        "tithi": "पूर्णिमा",
        "nakshatra": "रोहिणी",
        "timeWindow": "11:44 pm – 12:32 am",
        "score": "Excellent"
      },
      {
        "date": "Thu, 26 Nov",
        "isoDate": "2026-11-26",
        "weekday": 4,
        "tithi": "द्वितीया (कृ)",
        "nakshatra": "पुनर्वसु",
        "timeWindow": "11:45 pm – 12:33 am",
        "score": "Excellent"
      },
      {
        "date": "Fri, 27 Nov",
        "isoDate": "2026-11-27",
        "weekday": 5,
        "tithi": "तृतीया (कृ)",
        "nakshatra": "पुष्य",
        "timeWindow": "8:53 pm – 10:23 pm",
        "score": "Excellent"
      },
      {
        "date": "Mon, 30 Nov",
        "isoDate": "2026-11-30",
        "weekday": 1,
        "tithi": "सप्तमी (कृ)",
        "nakshatra": "पूर्व फल्गुनी",
        "timeWindow": "11:46 pm – 12:34 am",
        "score": "Excellent"
      }
    ]
  },
  {
    "name": "December 2026",
    "year": 2026,
    "monthNumber": 12,
    "entries": [
      {
        "date": "Tue, 1 Dec",
        "isoDate": "2026-12-01",
        "weekday": 2,
        "tithi": "अष्टमी (कृ)",
        "nakshatra": "उत्तर फल्गुनी",
        "timeWindow": "11:47 pm – 12:35 am",
        "score": "Good"
      },
      {
        "date": "Thu, 3 Dec",
        "isoDate": "2026-12-03",
        "weekday": 4,
        "tithi": "दशमी (कृ)",
        "nakshatra": "चित्रा",
        "timeWindow": "11:47 pm – 12:35 am",
        "score": "Good"
      },
      {
        "date": "Fri, 4 Dec",
        "isoDate": "2026-12-04",
        "weekday": 5,
        "tithi": "एकादशी (कृ)",
        "nakshatra": "स्वाती",
        "timeWindow": "8:59 pm – 10:29 pm",
        "score": "Good"
      },
      {
        "date": "Sun, 6 Dec",
        "isoDate": "2026-12-06",
        "weekday": 0,
        "tithi": "त्रयोदशी (कृ)",
        "nakshatra": "अनुराधा",
        "timeWindow": "11:49 pm – 12:37 am",
        "score": "Good"
      },
      {
        "date": "Thu, 10 Dec",
        "isoDate": "2026-12-10",
        "weekday": 4,
        "tithi": "प्रतिपदा",
        "nakshatra": "उत्तराषाढ़ा",
        "timeWindow": "11:50 pm – 12:38 am",
        "score": "Excellent"
      },
      {
        "date": "Fri, 11 Dec",
        "isoDate": "2026-12-11",
        "weekday": 5,
        "tithi": "द्वितीया",
        "nakshatra": "श्रवण",
        "timeWindow": "9:04 pm – 10:34 pm",
        "score": "Excellent"
      },
      {
        "date": "Mon, 14 Dec",
        "isoDate": "2026-12-14",
        "weekday": 1,
        "tithi": "पञ्चमी",
        "nakshatra": "शतभिषा",
        "timeWindow": "11:52 pm – 12:40 am",
        "score": "Excellent"
      },
      {
        "date": "Tue, 15 Dec",
        "isoDate": "2026-12-15",
        "weekday": 2,
        "tithi": "षष्ठी",
        "nakshatra": "पूर्वभाद्रपदा",
        "timeWindow": "11:53 pm – 12:41 am",
        "score": "Good"
      },
      {
        "date": "Wed, 16 Dec",
        "isoDate": "2026-12-16",
        "weekday": 3,
        "tithi": "सप्तमी",
        "nakshatra": "उत्तरभाद्रपदा",
        "timeWindow": "9:07 pm – 10:37 pm",
        "score": "Excellent"
      },
      {
        "date": "Thu, 17 Dec",
        "isoDate": "2026-12-17",
        "weekday": 4,
        "tithi": "अष्टमी",
        "nakshatra": "रेवती",
        "timeWindow": "11:54 pm – 12:42 am",
        "score": "Excellent"
      },
      {
        "date": "Fri, 18 Dec",
        "isoDate": "2026-12-18",
        "weekday": 5,
        "tithi": "नवमी",
        "nakshatra": "अश्विनी",
        "timeWindow": "9:08 pm – 10:38 pm",
        "score": "Excellent"
      },
      {
        "date": "Sun, 20 Dec",
        "isoDate": "2026-12-20",
        "weekday": 0,
        "tithi": "एकादशी",
        "nakshatra": "कृत्तिका",
        "timeWindow": "11:55 pm – 12:43 am",
        "score": "Okay"
      },
      {
        "date": "Mon, 21 Dec",
        "isoDate": "2026-12-21",
        "weekday": 1,
        "tithi": "द्वादशी",
        "nakshatra": "रोहिणी",
        "timeWindow": "11:55 pm – 12:43 am",
        "score": "Excellent"
      },
      {
        "date": "Tue, 22 Dec",
        "isoDate": "2026-12-22",
        "weekday": 2,
        "tithi": "त्रयोदशी",
        "nakshatra": "मृगशीर्षा",
        "timeWindow": "11:56 pm – 12:44 am",
        "score": "Good"
      },
      {
        "date": "Thu, 24 Dec",
        "isoDate": "2026-12-24",
        "weekday": 4,
        "tithi": "पूर्णिमा",
        "nakshatra": "पुनर्वसु",
        "timeWindow": "11:57 pm – 12:45 am",
        "score": "Excellent"
      },
      {
        "date": "Fri, 25 Dec",
        "isoDate": "2026-12-25",
        "weekday": 5,
        "tithi": "द्वितीया (कृ)",
        "nakshatra": "पुष्य",
        "timeWindow": "9:12 pm – 10:42 pm",
        "score": "Excellent"
      },
      {
        "date": "Sun, 27 Dec",
        "isoDate": "2026-12-27",
        "weekday": 0,
        "tithi": "चतुर्थी (कृ)",
        "nakshatra": "पूर्व फल्गुनी",
        "timeWindow": "11:58 pm – 12:46 am",
        "score": "Good"
      },
      {
        "date": "Mon, 28 Dec",
        "isoDate": "2026-12-28",
        "weekday": 1,
        "tithi": "पञ्चमी (कृ)",
        "nakshatra": "उत्तर फल्गुनी",
        "timeWindow": "11:59 pm – 12:47 am",
        "score": "Excellent"
      },
      {
        "date": "Wed, 30 Dec",
        "isoDate": "2026-12-30",
        "weekday": 3,
        "tithi": "सप्तमी (कृ)",
        "nakshatra": "चित्रा",
        "timeWindow": "9:14 pm – 10:44 pm",
        "score": "Okay"
      },
      {
        "date": "Thu, 31 Dec",
        "isoDate": "2026-12-31",
        "weekday": 4,
        "tithi": "अष्टमी (कृ)",
        "nakshatra": "स्वाती",
        "timeWindow": "12:00 am – 12:48 am",
        "score": "Good"
      }
    ]
  }
];
