import type { Language } from "../../store/onboardingSlice";

export const STRINGS = {
  english: {
    appTag: "Biodata, beautifully made",
    chooseLanguage: "Choose your language",
    role_title: "Who is this biodata for?",
    role_sub: "Begin the most important profile of a lifetime.",
    role_self: "For myself",
    role_self_desc: "I am creating my own biodata",
    role_parent: "For my child",
    role_parent_desc: "I am a parent finding a match for my son or daughter",
    next: "Continue",
    back: "Back",
    chooseFaith: "Your dharm",
    chooseFaithSub: "We tailor terminology and traditions to your community.",
    auth_title: "Sign in to continue",
    auth_sub: "Your biodata is private. Only you decide who sees it.",
    phone_label: "Phone number",
    send_otp: "Send OTP",
    or: "or",
    google: "Continue with Google",
    legal: "By continuing you agree to our Terms.",
    section_personal: "Personal",
    section_family: "Family",
    section_lineage: "Lineage",
    finish: "Save Biodata",
  },
  hindi: {
    appTag: "सुंदर बायोडेटा बनाइए",
    chooseLanguage: "अपनी भाषा चुनिए",
    role_title: "यह बायोडेटा किसके लिए है?",
    role_sub: "जीवन की सबसे महत्वपूर्ण प्रोफाइल बनाने की शुरुआत।",
    role_self: "अपने लिए",
    role_self_desc: "मैं अपना बायोडेटा बना रहा/रही हूँ",
    role_parent: "अपने बच्चे के लिए",
    role_parent_desc: "मैं अपने बेटे/बेटी के लिए रिश्ता ढूंढ रहा/रही हूँ",
    next: "आगे बढ़ें",
    back: "पीछे",
    chooseFaith: "आपका धर्म",
    chooseFaithSub: "हम आपके समुदाय के अनुसार शब्दावली और परंपराएँ रखते हैं।",
    auth_title: "जारी रखने के लिए साइन इन करें",
    auth_sub: "आपका बायोडेटा निजी है। आप तय करते हैं कौन देखेगा।",
    phone_label: "फ़ोन नंबर",
    send_otp: "OTP भेजें",
    or: "या",
    google: "Google से जारी रखें",
    legal: "आगे बढ़कर आप हमारी शर्तों से सहमत होते हैं।",
    section_personal: "व्यक्तिगत",
    section_family: "परिवार",
    section_lineage: "वंश",
    finish: "बायोडेटा सहेजें",
  },
  tamil: {
    appTag: "அழகான பயோடேட்டா",
    chooseLanguage: "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
    role_title: "இந்த பயோடேட்டா யாருக்கானது?",
    role_sub: "வாழ்க்கையின் மிக முக்கியமான சுயவிவரம்.",
    role_self: "எனக்காக",
    role_self_desc: "நான் எனது சொந்த பயோடேட்டா உருவாக்குகிறேன்",
    role_parent: "என் குழந்தைக்காக",
    role_parent_desc: "நான் என் மகன்/மகளுக்கு மணமகன்/மணமகள் தேடுகிறேன்",
    next: "தொடரவும்",
    back: "பின்",
    chooseFaith: "உங்கள் தர்மம்",
    chooseFaithSub: "உங்கள் சமூகத்திற்கேற்ப சொற்களையும் மரபுகளையும் வடிவமைக்கிறோம்.",
    auth_title: "தொடர உள்நுழையவும்",
    auth_sub: "உங்கள் பயோடேட்டா தனிப்பட்டது. யார் பார்க்க வேண்டுமென்பதை நீங்களே முடிவு செய்கிறீர்கள்.",
    phone_label: "தொலைபேசி எண்",
    send_otp: "OTP அனுப்பவும்",
    or: "அல்லது",
    google: "Google உடன் தொடரவும்",
    legal: "தொடர்வதன் மூலம் எங்கள் விதிமுறைகளை ஏற்கிறீர்கள்.",
    section_personal: "தனிப்பட்ட",
    section_family: "குடும்பம்",
    section_lineage: "வம்சாவளி",
    finish: "பயோடேட்டாவை சேமிக்கவும்",
  },
};

export function getStrings(language: Language) {
  return STRINGS[language] || STRINGS.english;
}
