import type { Language } from "../../store/onboardingSlice";

export const STRINGS = {
  english: {
    appTag: "Biodata, beautifully made",
    chooseLanguage: "Choose your language",
    role_title: "Who is this biodata for?",
    role_sub: "Begin the most important profile of a lifetime.",
    role_self: "For myself",
    role_self_desc: "I am creating my own biodata",
    role_parent: "For my child",
    role_parent_desc: "I am a parent finding a match for my son or daughter",
    next: "Continue",
    back: "Back",
    chooseFaith: "Your dharm",
    chooseFaithSub: "We tailor terminology and traditions to your community.",
    dharm_heading_line1: "Begin with",
    dharm_heading_line2: "your dharm.",
    auth_eyebrow: "Sign in",
    auth_title: "Sign in to continue",
    auth_sub: "Your biodata is private. Only you decide who sees it.",
    phone_label: "Phone number",
    send_otp: "Send OTP",
    sending: "Sending...",
    otp_sent_prefix: "We sent a 6-digit code to",
    verifying: "Verifying...",
    verify_continue: "Verify & Continue",
    change_number: "Change number",
    or: "or",
    google: "Continue with Google",
    legal: "By continuing you agree to our Terms.",
    section_personal: "Personal",
    section_family: "Family",
    section_lineage: "Lineage",
    biodata_label: "Biodata",
    form_heading_self_line1: "Your biodata,",
    form_heading_self_line2: "made with care.",
    form_heading_parent_line1: "The biodata for",
    form_heading_parent_line2: "your child.",
    form_subline_self: "Fill out each section thoughtfully. Every detail you share helps families understand who you are.",
    form_subline_parent: "Fill out each section thoughtfully. Every detail you share helps families understand who they are.",
    field_full_name: "Full name",
    field_child_full_name: "Your child's full name",
    field_dob: "Date of birth",
    field_current_city: "Current city",
    field_fathers_name: "Father's name",
    field_mothers_name: "Mother's name",
    field_community: "Community",
    field_gotra: "Gotra",
    form_save_hint: "Add full name & date of birth to save.",
    finish: "Save Biodata",
  },
  hindi: {
    appTag: "सुंदर बायोडेटा बनाइए",
    chooseLanguage: "अपनी भाषा चुनिए",
    role_title: "यह बायोडेटा किसके लिए है?",
    role_sub: "जीवन की सबसे महत्वपूर्ण प्रोफाइल बनाने की शुरुआत।",
    role_self: "अपने लिए",
    role_self_desc: "मैं अपना बायोडेटा बना रहा/रही हूँ",
    role_parent: "अपने बच्चे के लिए",
    role_parent_desc: "मैं अपने बेटे/बेटी के लिए रिश्ता ढूंढ रहा/रही हूँ",
    next: "आगे बढ़ें",
    back: "पीछे",
    chooseFaith: "आपका धर्म",
    chooseFaithSub: "हम आपके समुदाय के अनुसार शब्दावली और परंपराएँ रखते हैं।",
    dharm_heading_line1: "शुरुआत करें",
    dharm_heading_line2: "अपने धर्म से।",
    auth_eyebrow: "साइन इन करें",
    auth_title: "जारी रखने के लिए साइन इन करें",
    auth_sub: "आपका बायोडेटा निजी है। आप तय करते हैं कौन देखेगा।",
    phone_label: "फ़ोन नंबर",
    send_otp: "OTP भेजें",
    sending: "भेज रहे हैं...",
    otp_sent_prefix: "हमने 6-अंकीय कोड भेजा",
    verifying: "जाँच रहे हैं...",
    verify_continue: "जाँचें और जारी रखें",
    change_number: "नंबर बदलें",
    or: "या",
    google: "Google से जारी रखें",
    legal: "आगे बढ़कर आप हमारी शर्तों से सहमत होते हैं।",
    section_personal: "व्यक्तिगत",
    section_family: "परिवार",
    section_lineage: "वंश",
    biodata_label: "बायोडेटा",
    form_heading_self_line1: "आपका बायोडेटा,",
    form_heading_self_line2: "सोच के साथ बनाया।",
    form_heading_parent_line1: "बायोडेटा",
    form_heading_parent_line2: "आपके बच्चे के लिए।",
    form_subline_self: "हर अनुभाग को ध्यान से भरें। आप जो जानकारी साझा करते हैं, वह परिवारों को आपको समझने में मदद करती है।",
    form_subline_parent: "हर अनुभाग को ध्यान से भरें। आप जो जानकारी साझा करते हैं, वह परिवारों को आपके बच्चे को समझने में मदद करती है।",
    field_full_name: "पूरा नाम",
    field_child_full_name: "आपके बच्चे का पूरा नाम",
    field_dob: "जन्म तिथि",
    field_current_city: "वर्तमान शहर",
    field_fathers_name: "पिता का नाम",
    field_mothers_name: "माता का नाम",
    field_community: "समुदाय",
    field_gotra: "गोत्र",
    form_save_hint: "सहेजने के लिए पूरा नाम और जन्म तिथि दर्ज करें।",
    finish: "बायोडेटा सहेजें",
  },
  tamil: {
    appTag: "அழகான பயோடேட்டா",
    chooseLanguage: "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
    role_title: "இந்த பயோடேட்டா யாருக்கானது?",
    role_sub: "வாழ்க்கையின் மிக முக்கியமான சுயவிவரம்.",
    role_self: "எனக்காக",
    role_self_desc: "நான் எனது சொந்த பயோடேட்டா உருவாக்குகிறேன்",
    role_parent: "என் குழந்தைக்காக",
    role_parent_desc: "நான் என் மகன்/மகளுக்கு மணமகன்/மணமகள் தேடுகிறேன்",
    next: "தொடரவும்",
    back: "பின்",
    chooseFaith: "உங்கள் தர்மம்",
    chooseFaithSub: "உங்கள் சமூகத்திற்கேற்ப சொற்களையும் மரபுகளையும் வடிவமைக்கிறோம்.",
    dharm_heading_line1: "தொடங்குங்கள்",
    dharm_heading_line2: "உங்கள் தர்மத்தில்.",
    auth_eyebrow: "உள்நுழைவு",
    auth_title: "தொடர உள்நுழையவும்",
    auth_sub: "உங்கள் பயோடேட்டா தனிப்பட்டது. யார் பார்க்க வேண்டுமென்பதை நீங்களே முடிவு செய்கிறீர்கள்.",
    phone_label: "தொலைபேசி எண்",
    send_otp: "OTP அனுப்பவும்",
    sending: "அனுப்புகிறோம்...",
    otp_sent_prefix: "6-இலக்க குறியீட்டை அனுப்பினோம்",
    verifying: "சரிபார்க்கிறோம்...",
    verify_continue: "சரிபார்த்து தொடரவும்",
    change_number: "எண்ணை மாற்று",
    or: "அல்லது",
    google: "Google உடன் தொடரவும்",
    legal: "தொடர்வதன் மூலம் எங்கள் விதிமுறைகளை ஏற்கிறீர்கள்.",
    section_personal: "தனிப்பட்ட",
    section_family: "குடும்பம்",
    section_lineage: "வம்சாவளி",
    biodata_label: "பயோடேட்டா",
    form_heading_self_line1: "உங்கள் பயோடேட்டா,",
    form_heading_self_line2: "அக்கறையுடன் உருவாக்கப்பட்டது.",
    form_heading_parent_line1: "பயோடேட்டா",
    form_heading_parent_line2: "உங்கள் குழந்தைக்கானது.",
    form_subline_self: "ஒவ்வொரு பகுதியையும் கவனமாக நிரப்புங்கள். நீங்கள் பகிரும் விவரங்கள் குடும்பங்கள் உங்களை புரிந்துகொள்ள உதவும்.",
    form_subline_parent: "ஒவ்வொரு பகுதியையும் கவனமாக நிரப்புங்கள். நீங்கள் பகிரும் விவரங்கள் குடும்பங்கள் உங்கள் குழந்தையை புரிந்துகொள்ள உதவும்.",
    field_full_name: "முழு பெயர்",
    field_child_full_name: "உங்கள் குழந்தையின் முழு பெயர்",
    field_dob: "பிறந்த தேதி",
    field_current_city: "தற்போதைய நகரம்",
    field_fathers_name: "தந்தையின் பெயர்",
    field_mothers_name: "தாயின் பெயர்",
    field_community: "சமூகம்",
    field_gotra: "கோத்திரம்",
    form_save_hint: "சேமிக்க முழு பெயர் மற்றும் பிறந்த தேதி சேர்க்கவும்.",
    finish: "பயோடேட்டாவை சேமிக்கவும்",
  },
};

export function getStrings(language: Language) {
  return STRINGS[language] || STRINGS.english;
}
